/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { View } from "react-native";

const Divider: React.FC = () => (
  <View className="flex mt-2.5 w-full bg-zinc-300 min-h-[1px]" />
);

export default Divider;
