/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { View, Text, TouchableOpacity } from "react-native";

const CancelButton: React.FC = () => {
  return (
    <TouchableOpacity>
      <View className="flex-1 self-center px-6 py-1.5 mt-6 w-full text-xl font-bold leading-7 text-center text-rose-500 rounded-xl border-2 border-rose-500 border-solid min-h-[50px]">
        <Text>Hủy đơn</Text>
      </View>
    </TouchableOpacity>
  );
};

export default CancelButton;
