/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { View, Text } from "react-native";

interface PersonInfo {
  role: string;
  name: string;
  phone: string;
  address: string;
  colorClass: string;
}

const personData: PersonInfo[] = [
  {
    role: "Người nhận",
    name: "Thris Potato",
    phone: "092032xxxxx",
    address: "32/21/2 Nguyễn Thị Minh Khai",
    colorClass: "text-rose-500",
  },
  {
    role: "Người gửi",
    name: "Trí",
    phone: "032322xxxxx",
    address: "62/2/4 Phú Xuân, Nhà Bè",
    colorClass: "text-orange-500",
  },
];

const DeliveryInfo: React.FC = () => {
  return (
    <View className="flex flex-col mt-6 w-full rounded-3xl bg-zinc-50">
      <View className="text-xl font-bold leading-snug text-neutral-900">
        <Text>Thông tin giao nhận</Text>
      </View>
      <View className="flex flex-col mt-3 w-full text-base leading-none">
        {personData.map((person, index) => (
          <View
            key={index}
            className={`flex flex-col ${index > 0 ? "mt-5" : ""} w-full`}
          >
            <View className={`text-sm leading-none ${person.colorClass}`}>
              <Text>{person.role}</Text>
            </View>
            <View className="text-neutral-900">
              <Text>
                {person.name} - {person.phone}
              </Text>
            </View>
            <View className="text-neutral-500">
              <Text>{person.address}</Text>
            </View>
          </View>
        ))}
      </View>
    </View>
  );
};

export default DeliveryInfo;
