/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { View, Text, Image } from "react-native";
import Box from "../../svg/Box";
import Truck from "../../svg/Truck";
import Finish from "../../svg/Finish";


const statusData = [
  {
    status: "Chờ vận chuyển",
    icon: <Box />,
    active: true,
  },
  {
    status: "Đang vận chuyển",
    icon: <Truck />,
    active: true,
  },
  {
    status: "Nhận hàng",
    icon: <Finish />,
    active: false,
  },
];

const OrderStatus: React.FC = () => {
  return (
    <View className="flex gap-2 justify-center items-start mt-5 w-full">
      {statusData.map((item, index) => (
        <React.Fragment key={index}>
          <View
            className={`flex flex-col justify-center items-center text-xs leading-5 text-center ${
              item.active ? "text-teal-600" : "text-stone-300"
            }`}
          >
            <View className="object-contain w-7 aspect-square">
              {item.icon}
            </View>
            <View className="mt-2">
              <Text>
                {item.status.split(" ").map((word) => (
                  <React.Fragment key={word}>
                    {word}
                    <br />
                  </React.Fragment>
                ))}
              </Text>
            </View>
          </View>
          {index < statusData.length - 1 && (
            <View className="flex justify-center items-start self-stretch py-2.5 h-full">
              <Image
                source={{
                  uri: "https://cdn.builder.io/api/v1/image/assets/TEMP/f12bd6c9d5caeac29aff60b068069d613fc243a4293c0e39f920c7fc097bb8b1?placeholderIfAbsent=true&apiKey=ef30982ed39245199d22a158d999cd90",
                }}
                className="object-contain shrink-0 aspect-[12.66] w-[38px]"
              />
              <Image
                source={{
                  uri:
                    index === 0
                      ? "https://cdn.builder.io/api/v1/image/assets/TEMP/bedf0641f114be3e7104bf4bb9f787064599d35eb1157d75e862526493016782?placeholderIfAbsent=true&apiKey=ef30982ed39245199d22a158d999cd90"
                      : "https://cdn.builder.io/api/v1/image/assets/TEMP/47d96c0a32c1d9e527ed6490996cf1db9ea5e02dd658a0700e0ac52b9fa82e2a?placeholderIfAbsent=true&apiKey=ef30982ed39245199d22a158d999cd90",
                }}
                className="object-contain shrink-0 aspect-[14.29] w-[43px]"
              />
            </View>
          )}
        </React.Fragment>
      ))}
    </View>
  );
};

export default OrderStatus;
