/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { TouchableOpacity, Text } from "react-native";

interface ConfirmationButtonProps {
  onPress: () => void;
  variant: "outline" | "solid";
  children: React.ReactNode;
}

const ConfirmationButton: React.FC<ConfirmationButtonProps> = ({
  onPress,
  variant,
  children,
}) => {
  const baseClasses =
    "px-7 py-4 rounded-3xl border border-green-400 border-solid";
  const variantClasses =
    variant === "outline"
      ? "text-[#5DC061] bg-zinc-50"
      : "bg-[#5DC061] text-zinc-50";

  return (
    <TouchableOpacity
      onPress={onPress}
      className={`${baseClasses} ${variantClasses}`}
      accessibilityRole="button"
    >
      <Text className={`text-center font-bold ${variant === "solid" ? "text-white" : ""}`}>
      {children}
      </Text>
    </TouchableOpacity>
  );
};

export default ConfirmationButton;
