/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { View, Text } from "react-native";
import SectionItem, { SectionItemProps } from "./SectionItem";

interface AboutUsSectionProps {
  items: SectionItemProps[];
}

const AboutUsSection: React.FC<AboutUsSectionProps> = ({ items }) => (
  <View className="flex flex-col mt-6 w-full">
    <View className="text-3xl font-bold leading-none text-neutral-900">
      <Text>Về chúng tôi</Text>
    </View>
    <View className="flex flex-col mt-3 w-full text-xs leading-5 text-neutral-500">
      {items.map((item, index) => (
        <SectionItem key={index} {...item} />
      ))}
    </View>
  </View>
);

export default AboutUsSection;
