/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { View } from "react-native";
import AccountSection from "./AccountSection";
import UtilitiesSection from "./UtilitiesSection";
import AboutUsSection from "./AboutUsSection";
import { SectionItemProps } from "./SectionItem";
import Profile from "../../svg/Profile"
import Order from "../../svg/Order"
import Wallet from "../../svg/Wallet"
import History from "../../svg/History"
import Security from "../../svg/Security"
import Help from "../../svg/Help"
import Terms from "../../svg/Terms"
import Info from "../../svg/Info"
import Guides from "../../svg/Guides"
import Settings from "../../svg/Settings"

const accountItems: SectionItemProps[] = [
  {
    imageUri: <Profile />,
    text: "Thông tin cá nhân & Bảo mật",
  },
  {
    imageUri: <Order/>,
    text: "Đơn hàng của bạn",
  },
  {
    imageUri: <Wallet/>,
    text: "Ví của tôi",
  },
];

const utilitiesItems: SectionItemProps[] = [
  {
    imageUri: <History/>,
    text: "Lịch sử đơn hàng",
  },
  {
    imageUri: <Security/>,
    text: "Trung tâm bảo mật",
  },
];

const aboutUsItems: SectionItemProps[] = [
  {
    imageUri: <Help/>,
    text: "Trợ giúp",
  },
  {
    imageUri: <Terms/>,
    text: "Điều khoản",
  },
  {
    imageUri: <Info/>,
    text: "Giới thiệu",
  },
  {
    imageUri: <Guides/>,
    text: "Hướng dẫn sử dụng",
  },
  {
    imageUri: <Settings/>,
    text: "Cài đặt",
  },
];

const MyComponent: React.FC = () => {
  return (
    <View className="flex flex-col p-6 rounded-3xl max-w-[390px]">
      <AccountSection items={accountItems} />
      <UtilitiesSection items={utilitiesItems} />
      <AboutUsSection items={aboutUsItems} />
    </View>
  );
};

export default MyComponent;
