/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { View, Image, Text, TouchableOpacity } from "react-native";

export interface SectionItemProps {
  imageUri: string | React.ReactElement;
  text: string;
}

const SectionItem: React.FC<SectionItemProps> = ({ imageUri, text }) => (
  <TouchableOpacity className="flex-row gap-2 mt-2 w-full">
    {typeof imageUri === 'string' ? (
      <Image
        source={{ uri: imageUri }}
        className="object-contain shrink-0 my-auto w-6 aspect-square"
      />
    ) : (
      imageUri
    )}
    <View>
      <Text>{text}</Text>
    </View>
  </TouchableOpacity>
);

export default SectionItem;
